package com.chenkesi.order.transaction.domain.entity;

public class TransMessageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_message.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_message.service
     *
     * @mbggenerated
     */
    private String service;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_message.id
     *
     * @return the value of trans_message.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_message.id
     *
     * @param id the value for trans_message.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_message.service
     *
     * @return the value of trans_message.service
     *
     * @mbggenerated
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_message.service
     *
     * @param service the value for trans_message.service
     *
     * @mbggenerated
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }
}